In [3]:
import numpy as np

# Basic arrays

In [4]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([[1,2,3],[4,5,6]])
arr3 = np.array((7,8,9))
print(arr1, "\n=========\n", arr2, "\n==========\n", arr3)

[1 2 3 4] 
 [[1 2 3]
 [4 5 6]] 
 [7 8 9]


# Special arrays

In [7]:
zeros = np.zeros((2,3))
ones = np.ones((3,2))
identity = np.eye(3)
print(f"\n Special Arrays: \n zeros:\n {zeros}  \n\n ones:\n {ones}  \n\n identity :\n {identity}")


 Special Arrays: 
 zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]  

 ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]  

 identity :
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Empty and filled arrays

In [8]:
empty = np.empty((2,2))
full = np.full((2,2), 7)
print(f"\n empty Arrays: \n empty:\n {empty}  \n\n full:\n {full}")


 empty Arrays: 
 empty:
 [[2.12199579e-314 7.32088548e-312]
 [5.75092412e-321 8.28942550e-317]]  

 full:
 [[7 7]
 [7 7]]


# Arrays With Range

- arange: Use when you know the step/gap between two consecutive number
- linespace: Use when you know total the numbers

In [ ]:

range_arr = np.arange(0,10,2)
linespace_arr = np.linspace(0,1,5)
print(f"\n  Arrays: \n empty:\n {range_arr}  \n\n linspace:\n {linespace_arr}")


  Arrays: 
 empty:
 [0 2 4 6 8]  

 linspace:
 [0.   0.25 0.5  0.75 1.  ]


# Random Arrays

In [ ]:
rand = np.random.rand(2,3)
rand_int = np.random.randint(1,10,(2,2))
rand_normal = np.random.randn(2,3)
# distribution
rand_custom_normal = np.random.normal(5,2,(2,3)) #mean=5, std=2
print(f"\n  Arrays: \n rand:\n {rand}  \n\n rand_int:\n {rand_int}  \n\n rand_normal:\n {rand_normal} \n\n rand_custom_normal:\n {rand_custom_normal}")



  Arrays: 
 rand:
 [[0.90847399 0.16564141 0.13956193]
 [0.74224255 0.38397897 0.12425444]]  

 rand_int:
 [[6 4]
 [3 2]]  

 rand_normal:
 [[ 0.08153445 -0.97223882  1.22858647]
 [ 1.15899466 -0.82276125  0.8930084 ]] 

 rand_custom_normal:
 [[3.81748633 1.75513588 7.52007344]
 [6.07415713 6.40268215 5.89184   ]]


# Reshaping and initializing shapes

In [ ]:
reshaped = np.arange(12).reshape(3,4)
init_like = np.zeros_like(reshaped) # 3x4 zeros
print(f"\n  Arrays: \n reshaped:\n {reshaped}  \n\n init_like:\n {init_like}")



  Arrays: 
 reshaped:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]  

 init_like:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


# Numpy Indexing and Selection

In [ ]:
# Creating a sample array
arr = np.arange(0,11)
print("Initial array : ", arr)

# Bracket indexing and selection
# Get a value at index
print("value at index 8 : ",arr[8])

# Get values in range
print("values in range [1:5]", arr[1:5])
print("values in range [0:5]", arr[0:5])


Initial array :  [ 0  1  2  3  4  5  6  7  8  9 10]
value at index 8 :  8
values in range [1:5] [1 2 3 4]
values in range [0:5] [0 1 2 3 4]


## Broadcasting


In [23]:
# Setting values with index range
arr[0:5] = 100
print("After broadcasting [0:5] with 100", arr)

# reset array
arr = np.arange(0,11)
print("Reset array : ", arr)
# Important notes on slices
slice_of_arr = arr[0:6]
print("Slice of array [0:6]: ",slice_of_arr)

# Change slice
slice_of_arr[:] = 99
print("After modifying slice: ", slice_of_arr)
print("Original array after modifying : ", arr)

# to get a copy
arr_copy = arr.copy()
print("Copy of array : " , arr_copy)
arr_copy[:] = 22
print("After modifying slice: ", arr_copy)
print("Original array after modifying : ", arr)



After broadcasting [0:5] with 100 [100 100 100 100 100  99   6   7   8   9  10]
Reset array :  [ 0  1  2  3  4  5  6  7  8  9 10]
Slice of array [0:6]:  [0 1 2 3 4 5]
After modifying slice:  [99 99 99 99 99 99]
Original array after modifying :  [99 99 99 99 99 99  6  7  8  9 10]
Copy of array :  [99 99 99 99 99 99  6  7  8  9 10]
After modifying slice:  [22 22 22 22 22 22 22 22 22 22 22]
Original array after modifying :  [99 99 99 99 99 99  6  7  8  9 10]


In [28]:
# 2D arrays
arr_2d = np.array(([5,10,15],[20,25,30],[35,45,78]))
print("2D array : \n", arr_2d)

#Indexing Row
print("Second row of 2D array : ",arr_2d[1])

# Getting individual element value
print("Element at [1,0]: ",arr_2d[1][0])
print("Element at [1,0](alternative syntax): " ,arr_2d[1,0])

#2D array Slicing
print("Shape (2,2) from top right corner: \n", arr_2d[:2,1:])
print("Bootom row: ", arr_2d[2])
print("Bottom Row (alternative syntax): ",arr_2d[2,:])


2D array : 
 [[ 5 10 15]
 [20 25 30]
 [35 45 78]]
Second row of 2D array :  [20 25 30]
Element at [1,0]:  20
Element at [1,0](alternative syntax):  20
Shape (2,2) from top right corner: 
 [[10 15]
 [25 30]]
Bootom row:  [35 45 78]
Bottom Row (alternative syntax):  [35 45 78]


In [ ]:
# conditional selection

arr = np.arange(1,11)

# check condition
print("Condition arr > 4: ", arr>4)

# store Boolean result in another array
bool_arr = arr>4
print("Boolean array with condition arr > 4 : ", bool_arr)
# Select element where condition is true
print("Elements where condition is true", arr[bool_arr])
print("Element where condition is false : ", )


Condition arr > 4:  [False False False False  True  True  True  True  True  True]
Boolean array with condition arr > 4 :  [False False False False  True  True  True  True  True  True]
Elements where condition is true [ 5  6  7  8  9 10]



# Statistical Properties of Numpy arrays

In [4]:
arr = np.arange(0,10)
print(arr.shape)

# Summary Stats
print("Sum of elements : ", arr.sum())
print("Mean of elements : ", arr.mean())
print("Max elements : ", arr.max())
print("Min elements : ", arr.min())
print("Variance : ", arr.var())
print("Standard Deviation : ", arr.std())


(10,)
Sum of elements :  45
Mean of elements :  4.5
Max elements :  9
Min elements :  0
Variance :  8.25
Standard Deviation :  2.8722813232690143
