# NumPy

In [310]:
import numpy as np

In [311]:
# 1. Create an array of 10 zeros.
zeros = np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [312]:
# 2. Create an array of 10 ones.
ones = np.ones(10)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [313]:
# 3. Create an array of 10 fives.
fives = np.full(10, 5)
fives

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [314]:
# 4. Create an array of the integers from 10 to 50.
arr = np.arange(10, 51)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [315]:
# 5. Create an array of all the even integers from 10 to 50.
arr = np.arange(10, 51, 2)
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [316]:
# 6. Create a 3x3 matrix with values ranging from 0 to # 8.
matrix = np.arange(9).reshape(3, 3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [317]:
# 7. Create a 3x3 identity matrix.
identity_matrix = np.identity(3)
print(identity_matrix)
print("="*12)
identity_matrix_eye = np.eye(3)
print(identity_matrix_eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [318]:
# 8. Use NumPy to generate a random number between 0 and 1.
rand = np.random.rand()
rand

0.4659754334404982

In [319]:
# 9. Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution.
rand_arr = np.random.randn(25)
rand_arr

array([-0.94051379, -0.45673693, -0.61472936, -0.06387167,  0.34964949,
        1.54233147, -0.105658  , -0.20031379,  0.71244436,  0.89170565,
       -1.21934849, -0.49242124,  2.45199244, -2.09517708,  0.79792976,
       -1.35490876, -1.04971898, -1.03653028,  0.13732597, -0.03476503,
       -0.54542687,  0.44672055, -0.15590258,  1.52779305,  0.65178873])

In [320]:
# 10. Create an array of 20 linearly spaced points between 0 and 1.
linearly_space = np.linspace(0, 1, 20)
linearly_space

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [321]:
# 11. Create a 5x5 matrix with values from 1 to 25.
matrix = np.arange(1, 26).reshape(5, 5)
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [322]:
# 12. Extract the first row of a 2D array.
arr_2d = np.arange(12).reshape(3, 4)
print("arr_2d:\n", arr_2d)
print("first row:", arr_2d[0])
print("first row:", arr_2d[:1, :])

print("="*15)
arr_2d_1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("arr_2d_1:\n", arr_2d_1)
print("first row:", arr_2d_1[0])
print("first row:", arr_2d_1[:1, :])

arr_2d:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
first row: [0 1 2 3]
first row: [[0 1 2 3]]
arr_2d_1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
first row: [1 2 3]
first row: [[1 2 3]]


In [323]:
# 13. Extract the last column of a 2D array.
print("Arrays 2D:\n", arr_2d)
print("last column:", arr_2d[:, 3])
print("last column:", arr_2d[:, -1])
print("last column:\n", arr_2d[:, -1:])

Arrays 2D:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
last column: [ 3  7 11]
last column: [ 3  7 11]
last column:
 [[ 3]
 [ 7]
 [11]]


In [324]:
# 14. Find the sum of all elements in an array.
arr_sum_1d = np.array([1,2,5,7,9,10])
sum_1 = arr_sum_1d.sum()
print("Arrays:\n", arr_sum_1d)
print("Sum arr_sum_1d: ", sum_1)

arr_sum_2d = np.random.randint(1, 10, (3, 3))
sum_2 = arr_sum_2d.sum()
print("Arrays:\n", arr_sum_2d)
print("Sum arr_sum_1d: ", sum_2)

Arrays:
 [ 1  2  5  7  9 10]
Sum arr_sum_1d:  34
Arrays:
 [[2 2 3]
 [2 1 6]
 [3 1 7]]
Sum arr_sum_1d:  27


In [325]:
# 15. Find the standard deviation of an array.
std_1 = arr_sum_1d.std()
print("Arrays:\n", arr_sum_1d)
print("standard deviation: ", std_1)
print("="*15)
std_2 = arr_sum_2d.std()
print("Arrays:\n", arr_sum_2d)
print("standard deviation: ", std_2)

Arrays:
 [ 1  2  5  7  9 10]
standard deviation:  3.34995854037363
Arrays:
 [[2 2 3]
 [2 1 6]
 [3 1 7]]
standard deviation:  2.0


In [326]:
# 16. Find the index of the maximum value in an array.
max_val_1 = arr_sum_1d.max()
ind_max_val_1 = arr_sum_1d.argmax()
print("Arrays:\n", arr_sum_1d)
print(f"the maximum value {std_1} and indexs {ind_max_val_1}")
print("="*15)
max_val_2 = arr_sum_2d.max()
ind_max_val_2 = arr_sum_2d.max()
print("Arrays:\n", arr_sum_2d)
print(f"the maximum value {max_val_2} and indexs {ind_max_val_2}")

Arrays:
 [ 1  2  5  7  9 10]
the maximum value 3.34995854037363 and indexs 5
Arrays:
 [[2 2 3]
 [2 1 6]
 [3 1 7]]
the maximum value 7 and indexs 7


In [327]:
# 17. Sort an array in ascending order.
print("Arrays:\n", arr_sum_1d)
print("Arrays after sorted:\n", np.sort(arr_sum_1d))
print("="*40)
print("Arrays:\n", arr_sum_2d)
print("Arrays after sorted order by row:\n", np.sort(arr_sum_2d, axis=0)) # order by row
print("Arrays after sorted order by column:\n", np.sort(arr_sum_2d, axis=1)) # order by column

Arrays:
 [ 1  2  5  7  9 10]
Arrays after sorted:
 [ 1  2  5  7  9 10]
Arrays:
 [[2 2 3]
 [2 1 6]
 [3 1 7]]
Arrays after sorted order by row:
 [[2 1 3]
 [2 1 6]
 [3 2 7]]
Arrays after sorted order by column:
 [[2 2 3]
 [1 2 6]
 [1 3 7]]


In [328]:
# 18. Reverse an array.
print("Arrays:\n", arr_sum_1d)
print("Arrays after Reverse:\n", arr_sum_1d[::-1])
print("="*40)
print("Arrays:\n", arr_sum_2d)
print("Arrays after Reverse order by row:\n", arr_sum_2d[::-1]) # order by row
print("Arrays after Reverse order by column:\n", arr_sum_2d[:, ::-1]) # order by column

Arrays:
 [ 1  2  5  7  9 10]
Arrays after Reverse:
 [10  9  7  5  2  1]
Arrays:
 [[2 2 3]
 [2 1 6]
 [3 1 7]]
Arrays after Reverse order by row:
 [[3 1 7]
 [2 1 6]
 [2 2 3]]
Arrays after Reverse order by column:
 [[3 2 2]
 [6 1 2]
 [7 1 3]]


In [329]:
# 19. Create a diagonal matrix from a given array.
diagonal_matrix = np.diag([1,2,3])
print(diagonal_matrix)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [330]:
# 20. Create a 4x4 matrix with random integers between 1 and 100.
matrix = np.random.randint(1,100, (4,4))
matrix

array([[19,  6, 94,  1],
       [43, 17, 64, 17],
       [ 5, 69, 83, 63],
       [55, 73, 49, 22]])

# Pandas

In [331]:
import pandas as pd

In [332]:
# 1. Create a DataFrame with columns 'A', 'B', and 'C' and rows labeled 'Row1', 'Row2', and 'Row3'.
cols = ['A', 'B', 'C']
label_s = ['Row1', 'Row2', 'Row3']
data = np.random.randint(0,10,(3,3))
df = pd.DataFrame(data = data, columns=cols, index=label_s)
df

A  B  C
Row1  7  7  7
Row2  9  7  2
Row3  7  5  0

In [333]:
# 2. Select only the 'A' column from the DataFrame.
df['A']

Row1    7
Row2    9
Row3    7
Name: A, dtype: int32

In [334]:
# 3. Select both the 'A' and 'C' columns from the DataFrame.
df[['A','C']]

A  C
Row1  7  7
Row2  9  2
Row3  7  0

In [335]:
# 4. Select the row labeled 'Row2' from the DataFrame.
df.iloc[1]

A    9
B    7
C    2
Name: Row2, dtype: int32

In [336]:
# 5. Select the second row of the DataFrame using its position.
df.iloc[1]

A    9
B    7
C    2
Name: Row2, dtype: int32

In [337]:
# 6. Filter the DataFrame to include only rows where the value in column 'A' is greater than 1.
df['A'][df['A'] > 1]

Row1    7
Row2    9
Row3    7
Name: A, dtype: int32

In [338]:
# 7. Filter the DataFrame to include rows where 'A' is greater than 1 and 'B' is less than 6.

df[(df['A'] > 1) & (df['B'] < 6)]

A  B  C
Row3  7  5  0

In [339]:
# 8. Add a new column 'D' to the DataFrame that is the sum of columns 'A' and 'B'.
df['D'] = df['A'] + df['B']
df

A  B  C   D
Row1  7  7  7  14
Row2  9  7  2  16
Row3  7  5  0  12

In [340]:
# 9. Remove the column 'D' from the DataFrame.
df = df.drop('D', axis=1)
df

A  B  C
Row1  7  7  7
Row2  9  7  2
Row3  7  5  0

In [341]:
# 10. Group the DataFrame by the values in column 'A' and calculate the mean for other columns.
gr_a = df.groupby('A').mean()
gr_a

B    C
A          
7  6.0  3.5
9  7.0  2.0

In [342]:
# 11. Sort the DataFrame by the values in column 'B' in ascending order.
df_sorted = df.sort_values('B')
df_sorted

A  B  C
Row3  7  5  0
Row1  7  7  7
Row2  9  7  2

In [343]:
# 12. Sort the DataFrame by the values in column 'C' in descending order.
df_sorted2 = df.sort_values('C', ascending=False)
df_sorted2

A  B  C
Row1  7  7  7
Row2  9  7  2
Row3  7  5  0

In [344]:
# 13. Check which cells in the DataFrame have null values.
df.isnull().sum()

A    0
B    0
C    0
dtype: int64

In [345]:
# 14. Remove rows from the DataFrame that contain any null values.
df['D'] = [1, 2, None]
df

A  B  C    D
Row1  7  7  7  1.0
Row2  9  7  2  2.0
Row3  7  5  0  NaN

In [346]:
# 14. Remove rows from the DataFrame that contain any null values.
df = df.dropna()
df

A  B  C    D
Row1  7  7  7  1.0
Row2  9  7  2  2.0

In [347]:
x_row = pd.DataFrame(columns=df.columns, data=[[1,2,3,None]], index=df.index)
x_row

A  B  C     D
Row1  1  2  3  None
Row2  1  2  3  None

In [348]:
# 15. Fill null values in the DataFrame with the number 0.
# add one row has null values
df = pd.concat([df,x_row], axis=0)
df

C:\Users\dbda.STUDENTSDC\AppData\Local\Temp\ipykernel_13768\1495725374.py:3: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df,x_row], axis=0)


A  B  C    D
Row1  7  7  7  1.0
Row2  9  7  2  2.0
Row1  1  2  3  NaN
Row2  1  2  3  NaN

In [354]:
# 15. Fill null values in the DataFrame with the number 0.
df = df.fillna(0)
df

A  B  C    D
Row1  7  7  7  1.0
Row2  9  7  2  2.0
Row1  1  2  3  0.0
Row2  1  2  3  0.0

In [357]:
# 16. Merge the DataFrame with another DataFrame on the column 'A'.
another = pd.DataFrame(columns=['A', 'C'], data = [[7,2],[9,2],[1,2],[1,2]])
another


A  C
0  7  2
1  9  2
2  1  2
3  1  2

In [ ]:
# 16. Merge the DataFrame with another DataFrame on the column 'A'.
df_merge = pd.merge(df, another, on='A', how='inner')
df_merge

A  B  C_x    D  C_y
0  7  7    7  1.0    2
1  9  7    2  2.0    2
2  1  2    3  0.0    2
3  1  2    3  0.0    2
4  1  2    3  0.0    2
5  1  2    3  0.0    2

In [362]:
# 17. Concatenate the DataFrame with another DataFrame along the rows.
another2 = pd.DataFrame(columns=df_merge.columns, data = [[1,2,3,4,5]])
another2

A  B  C_x  D  C_y
0  1  2    3  4    5

In [ ]:
# 17. Concatenate the DataFrame with another DataFrame along the rows.
df_merge = pd.concat([df_merge,another2], axis=0)
df_merge

A  B  C_x    D  C_y
0  7  7    7  1.0    2
1  9  7    2  2.0    2
2  1  2    3  0.0    2
3  1  2    3  0.0    2
4  1  2    3  0.0    2
5  1  2    3  0.0    2
0  1  2    3  4.0    5

In [364]:
# 18. Reset the index of the DataFrame to start from 0.
df_merge = df_merge.reset_index()
df_merge

index  A  B  C_x    D  C_y
0      0  7  7    7  1.0    2
1      1  9  7    2  2.0    2
2      2  1  2    3  0.0    2
3      3  1  2    3  0.0    2
4      4  1  2    3  0.0    2
5      5  1  2    3  0.0    2
6      0  1  2    3  4.0    5

In [365]:
df

A  B  C    D
Row1  7  7  7  1.0
Row2  9  7  2  2.0
Row1  1  2  3  0.0
Row2  1  2  3  0.0

In [372]:
# 19. Create a summary of the DataFrame showing the count, mean, and standard deviation for each column.
for col_name in df:
    print("Column:", col_name)
    print("count", df[col_name].count())
    print("mean", df[col_name].mean())
    print("standard deviation", df[col_name].std())
    print("="*50)

Column: A
count 4
mean 4.5
standard deviation 4.123105625617661
Column: B
count 4
mean 4.5
standard deviation 2.886751345948129
Column: C
count 4
mean 3.75
standard deviation 2.217355782608345
Column: D
count 4
mean 0.75
standard deviation 0.9574271077563381


In [373]:
# 20. Count the number of unique values in column 'A'.
df.A.nunique()

3