# NumPy

In [1]:
import numpy as np

In [2]:
# 1. Create an array of 10 zeros.
zeros = np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
# 2. Create an array of 10 ones.
ones = np.ones(10)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
# 3. Create an array of 10 fives.
fives = np.full(10, 5)
fives

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [5]:
# 4. Create an array of the integers from 10 to 50.
arr = np.arange(10, 50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [6]:
# 5. Create an array of all the even integers from 10 to 50.
arr = np.arange(10, 50, 2)
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [8]:
# 6. Create a 3x3 matrix with values ranging from 0 to # 8.
matrix = np.arange(9).reshape(3, 3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
# 7. Create a 3x3 identity matrix.
identity_matrix = np.identity(3)
print(identity_matrix)
print("="*12)
identity_matrix_eye = np.eye(3)
print(identity_matrix_eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
# 8. Use NumPy to generate a random number between 0 and 1.
rand = np.random.rand()
rand

0.08027272663589669

In [16]:
# 9. Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution.
rand_arr = np.random.randn(25)
rand_arr

array([ 0.37708931, -1.59463301,  0.77946865, -0.28068625,  0.38016134,
        0.07862903,  0.20052883,  0.26463157, -1.53034453, -1.09685699,
       -1.15169549, -0.42008211,  0.29804899,  1.79241166,  0.07503812,
       -0.33920277, -0.29354285, -0.07952777,  0.93242893, -0.48067338,
       -0.95660275, -0.49425752,  0.89728026, -0.2543142 , -0.32482008])

In [19]:
# 10. Create an array of 20 linearly spaced points between 0 and 1.
linearly_space = np.linspace(0, 1, 20)
linearly_space

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [21]:
# 11. Create a 5x5 matrix with values from 1 to 25.
matrix = np.arange(1, 26).reshape(5, 5)
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [31]:
# 12. Extract the first row of a 2D array.
arr_2d = np.arange(12).reshape(3, 4)
print("arr_2d:\n", arr_2d)
print("first row:", arr_2d[0])
print("first row:", arr_2d[:1, :])

print("="*15)
arr_2d_1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("arr_2d_1:\n", arr_2d_1)
print("first row:", arr_2d_1[0])
print("first row:", arr_2d_1[:1, :])

arr_2d:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
first row: [0 1 2 3]
first row: [[0 1 2 3]]
arr_2d_1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
first row: [1 2 3]
first row: [[1 2 3]]


In [53]:
# 13. Extract the last column of a 2D array.
print("Arrays 2D:\n", arr_2d)
print("last column:", arr_2d[:, 3])
print("last column:", arr_2d[:, -1])
print("last column:\n", arr_2d[:, -1:])

Arrays 2D:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
last column: [ 3  7 11]
last column: [ 3  7 11]
last column:
 [[ 3]
 [ 7]
 [11]]


In [51]:
# 14. Find the sum of all elements in an array.
arr_sum_1d = np.array([1,2,5,7,9,10])
sum_1 = arr_sum_1d.sum()
print("Arrays:\n", arr_sum_1d)
print("Sum arr_sum_1d: ", sum_1)

arr_sum_2d = np.random.randint(1, 10, (3, 3))
sum_2 = arr_sum_2d.sum()
print("Arrays:\n", arr_sum_2d)
print("Sum arr_sum_1d: ", sum_2)

Arrays:
 [ 1  2  5  7  9 10]
Sum arr_sum_1d:  34
Arrays:
 [[7 2 7]
 [8 3 9]
 [7 1 6]]
Sum arr_sum_1d:  50


In [50]:
# 15. Find the standard deviation of an array.
std_1 = arr_sum_1d.std()
print("Arrays:\n", arr_sum_1d)
print("standard deviation: ", std_1)
print("="*15)
std_2 = arr_sum_2d.std()
print("Arrays:\n", arr_sum_2d)
print("standard deviation: ", std_2)

Arrays:
 [ 1  2  5  7  9 10]
standard deviation:  3.34995854037363
Arrays:
 [[5 2 1]
 [6 3 5]
 [6 4 3]]
standard deviation:  1.6629588385661962


In [49]:
# 16. Find the index of the maximum value in an array.
max_val_1 = arr_sum_1d.max()
ind_max_val_1 = arr_sum_1d.argmax()
print("Arrays:\n", arr_sum_1d)
print(f"the maximum value {std_1} and indexs {ind_max_val_1}")
print("="*15)
max_val_2 = arr_sum_2d.max()
ind_max_val_2 = arr_sum_2d.max()
print("Arrays:\n", arr_sum_2d)
print(f"the maximum value {max_val_2} and indexs {ind_max_val_2}")

Arrays:
 [ 1  2  5  7  9 10]
the maximum value 10 and indexs 5
Arrays:
 [[5 2 1]
 [6 3 5]
 [6 4 3]]
the maximum value 6 and indexs 6


In [62]:
# 17. Sort an array in ascending order.
print("Arrays:\n", arr_sum_1d)
print("Arrays after sorted:\n", np.sort(arr_sum_1d))
print("="*40)
print("Arrays:\n", arr_sum_2d)
print("Arrays after sorted order by row:\n", np.sort(arr_sum_2d, axis=0)) # order by row
print("Arrays after sorted order by column:\n", np.sort(arr_sum_2d, axis=1)) # order by column

Arrays:
 [ 1  2  5  7  9 10]
Arrays after sorted:
 [ 1  2  5  7  9 10]
Arrays:
 [[2 7 7]
 [3 8 9]
 [1 6 7]]
Arrays after sorted order by row:
 [[1 6 7]
 [2 7 7]
 [3 8 9]]
Arrays after sorted order by column:
 [[2 7 7]
 [3 8 9]
 [1 6 7]]


In [ ]:
# 18. Reverse an array.


In [ ]:
# 19. Create a diagonal matrix from a given array.


In [ ]:
# 20. Create a 4x4 matrix with random integers between 1 and 100.

# Pandas

In [ ]:

# 1. Create a DataFrame with columns 'A', 'B', and 'C' and rows labeled 'Row1', 'Row2', and 'Row3'.
# 2. Select only the 'A' column from the DataFrame.
# 3. Select both the 'A' and 'C' columns from the DataFrame.
# 4. Select the row labeled 'Row2' from the DataFrame.
# 5. Select the second row of the DataFrame using its position.
# 6. Filter the DataFrame to include only rows where the value in column 'A' is greater than 1.
# 7. Filter the DataFrame to include rows where 'A' is greater than 1 and 'B' is less than 6.

# 8. Add a new column 'D' to the DataFrame that is the sum of columns 'A' and 'B'.
# 9. Remove the column 'D' from the DataFrame.
# 10. Group the DataFrame by the values in column 'A' and calculate the mean for other columns.
# 11. Sort the DataFrame by the values in column 'B' in ascending order.
# 12. Sort the DataFrame by the values in column 'C' in descending order.
# 13. Check which cells in the DataFrame have null values.
# 14. Remove rows from the DataFrame that contain any null values.
# 15. Fill null values in the DataFrame with the number 0.
# 16. Merge the DataFrame with another DataFrame on the column 'A'.
# 17. Concatenate the DataFrame with another DataFrame along the rows.
# 18. Reset the index of the DataFrame to start from 0.
# 19. Create a summary of the DataFrame showing the count, mean, and standard deviation for each
column.
# 20. Count the number of unique values in column 'A'.